package com.iostreamonedemo.serialize.protobufdemo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person-entity.proto

public final class ListingAndGeneralNesting {
  private ListingAndGeneralNesting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .NestingObject object = 4;
    /**
     * <code>required .NestingObject object = 4;</code>
     */
    boolean hasObject();
    /**
     * <code>required .NestingObject object = 4;</code>
     */
    ListingAndGeneralNesting.NestingObject getObject();
    /**
     * <code>required .NestingObject object = 4;</code>
     */
    ListingAndGeneralNesting.NestingObjectOrBuilder getObjectOrBuilder();

    // required string name = 5;
    /**
     * <code>required string name = 5;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 5;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 5;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 clazz = 6;
    /**
     * <code>optional int32 clazz = 6;</code>
     */
    boolean hasClazz();
    /**
     * <code>optional int32 clazz = 6;</code>
     */
    int getClazz();
  }
  /**
   * Protobuf type {@code Person}
   *
   * <pre>
   *一个message可以看做是一个JavaBean，这样理解的话，如果message中还有message就类似于Java中的内部类了;
   *下面同时模拟属性是自定义类和集合的情况，一个人一套试卷，同时试卷有题目的集合属性
   * </pre>
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 34: {
              ListingAndGeneralNesting.NestingObject.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = object_.toBuilder();
              }
              object_ = input.readMessage(ListingAndGeneralNesting.NestingObject.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(object_);
                object_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 42: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              clazz_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ListingAndGeneralNesting.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ListingAndGeneralNesting.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListingAndGeneralNesting.Person.class, ListingAndGeneralNesting.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .NestingObject object = 4;
    public static final int OBJECT_FIELD_NUMBER = 4;
    private ListingAndGeneralNesting.NestingObject object_;
    /**
     * <code>required .NestingObject object = 4;</code>
     */
    public boolean hasObject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .NestingObject object = 4;</code>
     */
    public ListingAndGeneralNesting.NestingObject getObject() {
      return object_;
    }
    /**
     * <code>required .NestingObject object = 4;</code>
     */
    public ListingAndGeneralNesting.NestingObjectOrBuilder getObjectOrBuilder() {
      return object_;
    }

    // required string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    /**
     * <code>required string name = 5;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 clazz = 6;
    public static final int CLAZZ_FIELD_NUMBER = 6;
    private int clazz_;
    /**
     * <code>optional int32 clazz = 6;</code>
     */
    public boolean hasClazz() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 clazz = 6;</code>
     */
    public int getClazz() {
      return clazz_;
    }

    private void initFields() {
      object_ = ListingAndGeneralNesting.NestingObject.getDefaultInstance();
      name_ = "";
      clazz_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasObject()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getObject().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(4, object_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(6, clazz_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, object_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, clazz_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ListingAndGeneralNesting.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListingAndGeneralNesting.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListingAndGeneralNesting.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListingAndGeneralNesting.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListingAndGeneralNesting.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ListingAndGeneralNesting.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ListingAndGeneralNesting.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ListingAndGeneralNesting.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ListingAndGeneralNesting.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ListingAndGeneralNesting.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ListingAndGeneralNesting.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     *
     * <pre>
     *一个message可以看做是一个JavaBean，这样理解的话，如果message中还有message就类似于Java中的内部类了;
     *下面同时模拟属性是自定义类和集合的情况，一个人一套试卷，同时试卷有题目的集合属性
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ListingAndGeneralNesting.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ListingAndGeneralNesting.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ListingAndGeneralNesting.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ListingAndGeneralNesting.Person.class, ListingAndGeneralNesting.Person.Builder.class);
      }

      // Construct using ListingAndGeneralNesting.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getObjectFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (objectBuilder_ == null) {
          object_ = ListingAndGeneralNesting.NestingObject.getDefaultInstance();
        } else {
          objectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        clazz_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ListingAndGeneralNesting.internal_static_Person_descriptor;
      }

      public ListingAndGeneralNesting.Person getDefaultInstanceForType() {
        return ListingAndGeneralNesting.Person.getDefaultInstance();
      }

      public ListingAndGeneralNesting.Person build() {
        ListingAndGeneralNesting.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ListingAndGeneralNesting.Person buildPartial() {
        ListingAndGeneralNesting.Person result = new ListingAndGeneralNesting.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (objectBuilder_ == null) {
          result.object_ = object_;
        } else {
          result.object_ = objectBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clazz_ = clazz_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ListingAndGeneralNesting.Person) {
          return mergeFrom((ListingAndGeneralNesting.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ListingAndGeneralNesting.Person other) {
        if (other == ListingAndGeneralNesting.Person.getDefaultInstance()) return this;
        if (other.hasObject()) {
          mergeObject(other.getObject());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasClazz()) {
          setClazz(other.getClazz());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasObject()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!getObject().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ListingAndGeneralNesting.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ListingAndGeneralNesting.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .NestingObject object = 4;
      private ListingAndGeneralNesting.NestingObject object_ = ListingAndGeneralNesting.NestingObject.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ListingAndGeneralNesting.NestingObject, ListingAndGeneralNesting.NestingObject.Builder, ListingAndGeneralNesting.NestingObjectOrBuilder> objectBuilder_;
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      public boolean hasObject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      public ListingAndGeneralNesting.NestingObject getObject() {
        if (objectBuilder_ == null) {
          return object_;
        } else {
          return objectBuilder_.getMessage();
        }
      }
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      public Builder setObject(ListingAndGeneralNesting.NestingObject value) {
        if (objectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          object_ = value;
          onChanged();
        } else {
          objectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      public Builder setObject(
          ListingAndGeneralNesting.NestingObject.Builder builderForValue) {
        if (objectBuilder_ == null) {
          object_ = builderForValue.build();
          onChanged();
        } else {
          objectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      public Builder mergeObject(ListingAndGeneralNesting.NestingObject value) {
        if (objectBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              object_ != ListingAndGeneralNesting.NestingObject.getDefaultInstance()) {
            object_ =
              ListingAndGeneralNesting.NestingObject.newBuilder(object_).mergeFrom(value).buildPartial();
          } else {
            object_ = value;
          }
          onChanged();
        } else {
          objectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      public Builder clearObject() {
        if (objectBuilder_ == null) {
          object_ = ListingAndGeneralNesting.NestingObject.getDefaultInstance();
          onChanged();
        } else {
          objectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      public ListingAndGeneralNesting.NestingObject.Builder getObjectBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      public ListingAndGeneralNesting.NestingObjectOrBuilder getObjectOrBuilder() {
        if (objectBuilder_ != null) {
          return objectBuilder_.getMessageOrBuilder();
        } else {
          return object_;
        }
      }
      /**
       * <code>required .NestingObject object = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ListingAndGeneralNesting.NestingObject, ListingAndGeneralNesting.NestingObject.Builder, ListingAndGeneralNesting.NestingObjectOrBuilder> 
          getObjectFieldBuilder() {
        if (objectBuilder_ == null) {
          objectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ListingAndGeneralNesting.NestingObject, ListingAndGeneralNesting.NestingObject.Builder, ListingAndGeneralNesting.NestingObjectOrBuilder>(
                  object_,
                  getParentForChildren(),
                  isClean());
          object_ = null;
        }
        return objectBuilder_;
      }

      // required string name = 5;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 5;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 5;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 5;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 5;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 clazz = 6;
      private int clazz_ ;
      /**
       * <code>optional int32 clazz = 6;</code>
       */
      public boolean hasClazz() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 clazz = 6;</code>
       */
      public int getClazz() {
        return clazz_;
      }
      /**
       * <code>optional int32 clazz = 6;</code>
       */
      public Builder setClazz(int value) {
        bitField0_ |= 0x00000004;
        clazz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clazz = 6;</code>
       */
      public Builder clearClazz() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clazz_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  public interface NestingObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string title = 1;
    /**
     * <code>optional string title = 1;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // required int32 grade = 2;
    /**
     * <code>required int32 grade = 2;</code>
     */
    boolean hasGrade();
    /**
     * <code>required int32 grade = 2;</code>
     */
    int getGrade();

    // repeated string subject = 3;
    /**
     * <code>repeated string subject = 3;</code>
     */
    java.util.List<java.lang.String>
    getSubjectList();
    /**
     * <code>repeated string subject = 3;</code>
     */
    int getSubjectCount();
    /**
     * <code>repeated string subject = 3;</code>
     */
    java.lang.String getSubject(int index);
    /**
     * <code>repeated string subject = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes(int index);
  }
  /**
   * Protobuf type {@code NestingObject}
   */
  public static final class NestingObject extends
      com.google.protobuf.GeneratedMessage
      implements NestingObjectOrBuilder {
    // Use NestingObject.newBuilder() to construct.
    private NestingObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NestingObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NestingObject defaultInstance;
    public static NestingObject getDefaultInstance() {
      return defaultInstance;
    }

    public NestingObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NestingObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              title_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              grade_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                subject_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              subject_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          subject_ = new com.google.protobuf.UnmodifiableLazyStringList(subject_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ListingAndGeneralNesting.internal_static_NestingObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ListingAndGeneralNesting.internal_static_NestingObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListingAndGeneralNesting.NestingObject.class, ListingAndGeneralNesting.NestingObject.Builder.class);
    }

    public static com.google.protobuf.Parser<NestingObject> PARSER =
        new com.google.protobuf.AbstractParser<NestingObject>() {
      public NestingObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NestingObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NestingObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string title = 1;
    public static final int TITLE_FIELD_NUMBER = 1;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 1;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 grade = 2;
    public static final int GRADE_FIELD_NUMBER = 2;
    private int grade_;
    /**
     * <code>required int32 grade = 2;</code>
     */
    public boolean hasGrade() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 grade = 2;</code>
     */
    public int getGrade() {
      return grade_;
    }

    // repeated string subject = 3;
    public static final int SUBJECT_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList subject_;
    /**
     * <code>repeated string subject = 3;</code>
     */
    public java.util.List<java.lang.String>
        getSubjectList() {
      return subject_;
    }
    /**
     * <code>repeated string subject = 3;</code>
     */
    public int getSubjectCount() {
      return subject_.size();
    }
    /**
     * <code>repeated string subject = 3;</code>
     */
    public java.lang.String getSubject(int index) {
      return subject_.get(index);
    }
    /**
     * <code>repeated string subject = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes(int index) {
      return subject_.getByteString(index);
    }

    private void initFields() {
      title_ = "";
      grade_ = 0;
      subject_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGrade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, grade_);
      }
      for (int i = 0; i < subject_.size(); i++) {
        output.writeBytes(3, subject_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, grade_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < subject_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(subject_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSubjectList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ListingAndGeneralNesting.NestingObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListingAndGeneralNesting.NestingObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListingAndGeneralNesting.NestingObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListingAndGeneralNesting.NestingObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListingAndGeneralNesting.NestingObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ListingAndGeneralNesting.NestingObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ListingAndGeneralNesting.NestingObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ListingAndGeneralNesting.NestingObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ListingAndGeneralNesting.NestingObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ListingAndGeneralNesting.NestingObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ListingAndGeneralNesting.NestingObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NestingObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ListingAndGeneralNesting.NestingObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ListingAndGeneralNesting.internal_static_NestingObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ListingAndGeneralNesting.internal_static_NestingObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ListingAndGeneralNesting.NestingObject.class, ListingAndGeneralNesting.NestingObject.Builder.class);
      }

      // Construct using ListingAndGeneralNesting.NestingObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        grade_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        subject_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ListingAndGeneralNesting.internal_static_NestingObject_descriptor;
      }

      public ListingAndGeneralNesting.NestingObject getDefaultInstanceForType() {
        return ListingAndGeneralNesting.NestingObject.getDefaultInstance();
      }

      public ListingAndGeneralNesting.NestingObject build() {
        ListingAndGeneralNesting.NestingObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ListingAndGeneralNesting.NestingObject buildPartial() {
        ListingAndGeneralNesting.NestingObject result = new ListingAndGeneralNesting.NestingObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.grade_ = grade_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          subject_ = new com.google.protobuf.UnmodifiableLazyStringList(
              subject_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.subject_ = subject_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ListingAndGeneralNesting.NestingObject) {
          return mergeFrom((ListingAndGeneralNesting.NestingObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ListingAndGeneralNesting.NestingObject other) {
        if (other == ListingAndGeneralNesting.NestingObject.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          bitField0_ |= 0x00000001;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasGrade()) {
          setGrade(other.getGrade());
        }
        if (!other.subject_.isEmpty()) {
          if (subject_.isEmpty()) {
            subject_ = other.subject_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSubjectIsMutable();
            subject_.addAll(other.subject_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGrade()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ListingAndGeneralNesting.NestingObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ListingAndGeneralNesting.NestingObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string title = 1;
      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 1;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }

      // required int32 grade = 2;
      private int grade_ ;
      /**
       * <code>required int32 grade = 2;</code>
       */
      public boolean hasGrade() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 grade = 2;</code>
       */
      public int getGrade() {
        return grade_;
      }
      /**
       * <code>required int32 grade = 2;</code>
       */
      public Builder setGrade(int value) {
        bitField0_ |= 0x00000002;
        grade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 grade = 2;</code>
       */
      public Builder clearGrade() {
        bitField0_ = (bitField0_ & ~0x00000002);
        grade_ = 0;
        onChanged();
        return this;
      }

      // repeated string subject = 3;
      private com.google.protobuf.LazyStringList subject_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSubjectIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          subject_ = new com.google.protobuf.LazyStringArrayList(subject_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public java.util.List<java.lang.String>
          getSubjectList() {
        return java.util.Collections.unmodifiableList(subject_);
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public int getSubjectCount() {
        return subject_.size();
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public java.lang.String getSubject(int index) {
        return subject_.get(index);
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes(int index) {
        return subject_.getByteString(index);
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public Builder setSubject(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSubjectIsMutable();
        subject_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public Builder addSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSubjectIsMutable();
        subject_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public Builder addAllSubject(
          java.lang.Iterable<java.lang.String> values) {
        ensureSubjectIsMutable();
        super.addAll(values, subject_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public Builder clearSubject() {
        subject_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string subject = 3;</code>
       */
      public Builder addSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSubjectIsMutable();
        subject_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NestingObject)
    }

    static {
      defaultInstance = new NestingObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NestingObject)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NestingObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NestingObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036listingAndGeneralNesting.proto\"E\n\006Pers" +
      "on\022\036\n\006object\030\004 \002(\0132\016.NestingObject\022\014\n\004na" +
      "me\030\005 \002(\t\022\r\n\005clazz\030\006 \001(\005\">\n\rNestingObject" +
      "\022\r\n\005title\030\001 \001(\t\022\r\n\005grade\030\002 \002(\005\022\017\n\007subjec" +
      "t\030\003 \003(\tB\032B\030ListingAndGeneralNesting"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_descriptor,
              new java.lang.String[] { "Object", "Name", "Clazz", });
          internal_static_NestingObject_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NestingObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NestingObject_descriptor,
              new java.lang.String[] { "Title", "Grade", "Subject", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
