package com.iostreamonedemo.serialize.protobufdemo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person-entity.proto

public final class MapAndCustomNesting {
  private MapAndCustomNesting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();
  }
  /**
   * <pre>
   *一个message可以看做是一个JavaBean，这样理解的话，如果message中还有message就类似于Java中的内部类了;
   *下面模拟map格式和元素是用户自定义类对象的list格式
   * </pre>
   *
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      age_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MapAndCustomNesting.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MapAndCustomNesting.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MapAndCustomNesting.Person.class, MapAndCustomNesting.Person.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MapAndCustomNesting.Person)) {
        return super.equals(obj);
      }
      MapAndCustomNesting.Person other = (MapAndCustomNesting.Person) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasAge() == other.hasAge());
      if (hasAge()) {
        result = result && (getAge()
            == other.getAge());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MapAndCustomNesting.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MapAndCustomNesting.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MapAndCustomNesting.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MapAndCustomNesting.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MapAndCustomNesting.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MapAndCustomNesting.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MapAndCustomNesting.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MapAndCustomNesting.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *一个message可以看做是一个JavaBean，这样理解的话，如果message中还有message就类似于Java中的内部类了;
     *下面模拟map格式和元素是用户自定义类对象的list格式
     * </pre>
     *
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        MapAndCustomNesting.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MapAndCustomNesting.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MapAndCustomNesting.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MapAndCustomNesting.Person.class, MapAndCustomNesting.Person.Builder.class);
      }

      // Construct using MapAndCustomNesting.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MapAndCustomNesting.internal_static_Person_descriptor;
      }

      public MapAndCustomNesting.Person getDefaultInstanceForType() {
        return MapAndCustomNesting.Person.getDefaultInstance();
      }

      public MapAndCustomNesting.Person build() {
        MapAndCustomNesting.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MapAndCustomNesting.Person buildPartial() {
        MapAndCustomNesting.Person result = new MapAndCustomNesting.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.age_ = age_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MapAndCustomNesting.Person) {
          return mergeFrom((MapAndCustomNesting.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MapAndCustomNesting.Person other) {
        if (other == MapAndCustomNesting.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MapAndCustomNesting.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MapAndCustomNesting.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final MapAndCustomNesting.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MapAndCustomNesting.Person();
    }

    public static MapAndCustomNesting.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public MapAndCustomNesting.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Lists)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Person subject = 3;</code>
     */
    java.util.List<MapAndCustomNesting.Person> 
        getSubjectList();
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    MapAndCustomNesting.Person getSubject(int index);
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    int getSubjectCount();
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    java.util.List<? extends MapAndCustomNesting.PersonOrBuilder> 
        getSubjectOrBuilderList();
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    MapAndCustomNesting.PersonOrBuilder getSubjectOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Lists}
   */
  public  static final class Lists extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Lists)
      ListsOrBuilder {
    // Use Lists.newBuilder() to construct.
    private Lists(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Lists() {
      subject_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Lists(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                subject_ = new java.util.ArrayList<MapAndCustomNesting.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              subject_.add(
                  input.readMessage(MapAndCustomNesting.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          subject_ = java.util.Collections.unmodifiableList(subject_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MapAndCustomNesting.internal_static_Lists_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MapAndCustomNesting.internal_static_Lists_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MapAndCustomNesting.Lists.class, MapAndCustomNesting.Lists.Builder.class);
    }

    public static final int SUBJECT_FIELD_NUMBER = 3;
    private java.util.List<MapAndCustomNesting.Person> subject_;
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    public java.util.List<MapAndCustomNesting.Person> getSubjectList() {
      return subject_;
    }
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    public java.util.List<? extends MapAndCustomNesting.PersonOrBuilder> 
        getSubjectOrBuilderList() {
      return subject_;
    }
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    public int getSubjectCount() {
      return subject_.size();
    }
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    public MapAndCustomNesting.Person getSubject(int index) {
      return subject_.get(index);
    }
    /**
     * <code>repeated .Person subject = 3;</code>
     */
    public MapAndCustomNesting.PersonOrBuilder getSubjectOrBuilder(
        int index) {
      return subject_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSubjectCount(); i++) {
        if (!getSubject(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < subject_.size(); i++) {
        output.writeMessage(3, subject_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < subject_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, subject_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MapAndCustomNesting.Lists)) {
        return super.equals(obj);
      }
      MapAndCustomNesting.Lists other = (MapAndCustomNesting.Lists) obj;

      boolean result = true;
      result = result && getSubjectList()
          .equals(other.getSubjectList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSubjectCount() > 0) {
        hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getSubjectList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MapAndCustomNesting.Lists parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MapAndCustomNesting.Lists parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MapAndCustomNesting.Lists parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MapAndCustomNesting.Lists parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MapAndCustomNesting.Lists parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Lists parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MapAndCustomNesting.Lists parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Lists parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MapAndCustomNesting.Lists parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Lists parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MapAndCustomNesting.Lists prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Lists}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Lists)
        MapAndCustomNesting.ListsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MapAndCustomNesting.internal_static_Lists_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MapAndCustomNesting.internal_static_Lists_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MapAndCustomNesting.Lists.class, MapAndCustomNesting.Lists.Builder.class);
      }

      // Construct using MapAndCustomNesting.Lists.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSubjectFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (subjectBuilder_ == null) {
          subject_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          subjectBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MapAndCustomNesting.internal_static_Lists_descriptor;
      }

      public MapAndCustomNesting.Lists getDefaultInstanceForType() {
        return MapAndCustomNesting.Lists.getDefaultInstance();
      }

      public MapAndCustomNesting.Lists build() {
        MapAndCustomNesting.Lists result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MapAndCustomNesting.Lists buildPartial() {
        MapAndCustomNesting.Lists result = new MapAndCustomNesting.Lists(this);
        int from_bitField0_ = bitField0_;
        if (subjectBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            subject_ = java.util.Collections.unmodifiableList(subject_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.subject_ = subject_;
        } else {
          result.subject_ = subjectBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MapAndCustomNesting.Lists) {
          return mergeFrom((MapAndCustomNesting.Lists)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MapAndCustomNesting.Lists other) {
        if (other == MapAndCustomNesting.Lists.getDefaultInstance()) return this;
        if (subjectBuilder_ == null) {
          if (!other.subject_.isEmpty()) {
            if (subject_.isEmpty()) {
              subject_ = other.subject_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSubjectIsMutable();
              subject_.addAll(other.subject_);
            }
            onChanged();
          }
        } else {
          if (!other.subject_.isEmpty()) {
            if (subjectBuilder_.isEmpty()) {
              subjectBuilder_.dispose();
              subjectBuilder_ = null;
              subject_ = other.subject_;
              bitField0_ = (bitField0_ & ~0x00000001);
              subjectBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubjectFieldBuilder() : null;
            } else {
              subjectBuilder_.addAllMessages(other.subject_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSubjectCount(); i++) {
          if (!getSubject(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MapAndCustomNesting.Lists parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MapAndCustomNesting.Lists) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<MapAndCustomNesting.Person> subject_ =
        java.util.Collections.emptyList();
      private void ensureSubjectIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          subject_ = new java.util.ArrayList<MapAndCustomNesting.Person>(subject_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MapAndCustomNesting.Person, MapAndCustomNesting.Person.Builder, MapAndCustomNesting.PersonOrBuilder> subjectBuilder_;

      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public java.util.List<MapAndCustomNesting.Person> getSubjectList() {
        if (subjectBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subject_);
        } else {
          return subjectBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public int getSubjectCount() {
        if (subjectBuilder_ == null) {
          return subject_.size();
        } else {
          return subjectBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public MapAndCustomNesting.Person getSubject(int index) {
        if (subjectBuilder_ == null) {
          return subject_.get(index);
        } else {
          return subjectBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder setSubject(
          int index, MapAndCustomNesting.Person value) {
        if (subjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectIsMutable();
          subject_.set(index, value);
          onChanged();
        } else {
          subjectBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder setSubject(
          int index, MapAndCustomNesting.Person.Builder builderForValue) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          subject_.set(index, builderForValue.build());
          onChanged();
        } else {
          subjectBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder addSubject(MapAndCustomNesting.Person value) {
        if (subjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectIsMutable();
          subject_.add(value);
          onChanged();
        } else {
          subjectBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder addSubject(
          int index, MapAndCustomNesting.Person value) {
        if (subjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectIsMutable();
          subject_.add(index, value);
          onChanged();
        } else {
          subjectBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder addSubject(
          MapAndCustomNesting.Person.Builder builderForValue) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          subject_.add(builderForValue.build());
          onChanged();
        } else {
          subjectBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder addSubject(
          int index, MapAndCustomNesting.Person.Builder builderForValue) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          subject_.add(index, builderForValue.build());
          onChanged();
        } else {
          subjectBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder addAllSubject(
          java.lang.Iterable<? extends MapAndCustomNesting.Person> values) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subject_);
          onChanged();
        } else {
          subjectBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder clearSubject() {
        if (subjectBuilder_ == null) {
          subject_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          subjectBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public Builder removeSubject(int index) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          subject_.remove(index);
          onChanged();
        } else {
          subjectBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public MapAndCustomNesting.Person.Builder getSubjectBuilder(
          int index) {
        return getSubjectFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public MapAndCustomNesting.PersonOrBuilder getSubjectOrBuilder(
          int index) {
        if (subjectBuilder_ == null) {
          return subject_.get(index);  } else {
          return subjectBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public java.util.List<? extends MapAndCustomNesting.PersonOrBuilder> 
           getSubjectOrBuilderList() {
        if (subjectBuilder_ != null) {
          return subjectBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subject_);
        }
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public MapAndCustomNesting.Person.Builder addSubjectBuilder() {
        return getSubjectFieldBuilder().addBuilder(
            MapAndCustomNesting.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public MapAndCustomNesting.Person.Builder addSubjectBuilder(
          int index) {
        return getSubjectFieldBuilder().addBuilder(
            index, MapAndCustomNesting.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .Person subject = 3;</code>
       */
      public java.util.List<MapAndCustomNesting.Person.Builder> 
           getSubjectBuilderList() {
        return getSubjectFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MapAndCustomNesting.Person, MapAndCustomNesting.Person.Builder, MapAndCustomNesting.PersonOrBuilder> 
          getSubjectFieldBuilder() {
        if (subjectBuilder_ == null) {
          subjectBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MapAndCustomNesting.Person, MapAndCustomNesting.Person.Builder, MapAndCustomNesting.PersonOrBuilder>(
                  subject_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          subject_ = null;
        }
        return subjectBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Lists)
    }

    // @@protoc_insertion_point(class_scope:Lists)
    private static final MapAndCustomNesting.Lists DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MapAndCustomNesting.Lists();
    }

    public static MapAndCustomNesting.Lists getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Lists>
        PARSER = new com.google.protobuf.AbstractParser<Lists>() {
      public Lists parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Lists(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Lists> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Lists> getParserForType() {
      return PARSER;
    }

    public MapAndCustomNesting.Lists getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MapsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Maps)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */
    int getMapsCount();
    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */
    boolean containsMaps(
        java.lang.String key);
    /**
     * Use {@link #getMapsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, MapAndCustomNesting.Person>
    getMaps();
    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */
    java.util.Map<java.lang.String, MapAndCustomNesting.Person>
    getMapsMap();
    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */

    MapAndCustomNesting.Person getMapsOrDefault(
        java.lang.String key,
        MapAndCustomNesting.Person defaultValue);
    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */

    MapAndCustomNesting.Person getMapsOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   *protobufdemo 2.5.0版本不能编译，会报错 Expected "required", "optional", or "repeated".和 Expected field name.
   * </pre>
   *
   * Protobuf type {@code Maps}
   */
  public  static final class Maps extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Maps)
      MapsOrBuilder {
    // Use Maps.newBuilder() to construct.
    private Maps(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Maps() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Maps(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                maps_ = com.google.protobuf.MapField.newMapField(
                    MapsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, MapAndCustomNesting.Person>
              maps__ = input.readMessage(
                  MapsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              maps_.getMutableMap().put(
                  maps__.getKey(), maps__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MapAndCustomNesting.internal_static_Maps_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMaps();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MapAndCustomNesting.internal_static_Maps_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MapAndCustomNesting.Maps.class, MapAndCustomNesting.Maps.Builder.class);
    }

    public static final int MAPS_FIELD_NUMBER = 4;
    private static final class MapsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, MapAndCustomNesting.Person> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, MapAndCustomNesting.Person>newDefaultInstance(
                  MapAndCustomNesting.internal_static_Maps_MapsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  MapAndCustomNesting.Person.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, MapAndCustomNesting.Person> maps_;
    private com.google.protobuf.MapField<java.lang.String, MapAndCustomNesting.Person>
    internalGetMaps() {
      if (maps_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapsDefaultEntryHolder.defaultEntry);
      }
      return maps_;
    }

    public int getMapsCount() {
      return internalGetMaps().getMap().size();
    }
    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */

    public boolean containsMaps(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMaps().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, MapAndCustomNesting.Person> getMaps() {
      return getMapsMap();
    }
    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */

    public java.util.Map<java.lang.String, MapAndCustomNesting.Person> getMapsMap() {
      return internalGetMaps().getMap();
    }
    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */

    public MapAndCustomNesting.Person getMapsOrDefault(
        java.lang.String key,
        MapAndCustomNesting.Person defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, MapAndCustomNesting.Person> map =
          internalGetMaps().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .Person&gt; maps = 4;</code>
     */

    public MapAndCustomNesting.Person getMapsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, MapAndCustomNesting.Person> map =
          internalGetMaps().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (MapAndCustomNesting.Person item : getMapsMap().values()) {
        if (!item.isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMaps(),
          MapsDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, MapAndCustomNesting.Person> entry
           : internalGetMaps().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, MapAndCustomNesting.Person>
        maps__ = MapsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, maps__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MapAndCustomNesting.Maps)) {
        return super.equals(obj);
      }
      MapAndCustomNesting.Maps other = (MapAndCustomNesting.Maps) obj;

      boolean result = true;
      result = result && internalGetMaps().equals(
          other.internalGetMaps());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetMaps().getMap().isEmpty()) {
        hash = (37 * hash) + MAPS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMaps().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MapAndCustomNesting.Maps parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MapAndCustomNesting.Maps parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MapAndCustomNesting.Maps parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MapAndCustomNesting.Maps parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MapAndCustomNesting.Maps parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Maps parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MapAndCustomNesting.Maps parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Maps parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MapAndCustomNesting.Maps parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MapAndCustomNesting.Maps parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MapAndCustomNesting.Maps prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *protobufdemo 2.5.0版本不能编译，会报错 Expected "required", "optional", or "repeated".和 Expected field name.
     * </pre>
     *
     * Protobuf type {@code Maps}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Maps)
        MapAndCustomNesting.MapsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MapAndCustomNesting.internal_static_Maps_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMaps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableMaps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MapAndCustomNesting.internal_static_Maps_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MapAndCustomNesting.Maps.class, MapAndCustomNesting.Maps.Builder.class);
      }

      // Construct using MapAndCustomNesting.Maps.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableMaps().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MapAndCustomNesting.internal_static_Maps_descriptor;
      }

      public MapAndCustomNesting.Maps getDefaultInstanceForType() {
        return MapAndCustomNesting.Maps.getDefaultInstance();
      }

      public MapAndCustomNesting.Maps build() {
        MapAndCustomNesting.Maps result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MapAndCustomNesting.Maps buildPartial() {
        MapAndCustomNesting.Maps result = new MapAndCustomNesting.Maps(this);
        int from_bitField0_ = bitField0_;
        result.maps_ = internalGetMaps();
        result.maps_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MapAndCustomNesting.Maps) {
          return mergeFrom((MapAndCustomNesting.Maps)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MapAndCustomNesting.Maps other) {
        if (other == MapAndCustomNesting.Maps.getDefaultInstance()) return this;
        internalGetMutableMaps().mergeFrom(
            other.internalGetMaps());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (MapAndCustomNesting.Person item : getMapsMap().values()) {
          if (!item.isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MapAndCustomNesting.Maps parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MapAndCustomNesting.Maps) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, MapAndCustomNesting.Person> maps_;
      private com.google.protobuf.MapField<java.lang.String, MapAndCustomNesting.Person>
      internalGetMaps() {
        if (maps_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapsDefaultEntryHolder.defaultEntry);
        }
        return maps_;
      }
      private com.google.protobuf.MapField<java.lang.String, MapAndCustomNesting.Person>
      internalGetMutableMaps() {
        onChanged();;
        if (maps_ == null) {
          maps_ = com.google.protobuf.MapField.newMapField(
              MapsDefaultEntryHolder.defaultEntry);
        }
        if (!maps_.isMutable()) {
          maps_ = maps_.copy();
        }
        return maps_;
      }

      public int getMapsCount() {
        return internalGetMaps().getMap().size();
      }
      /**
       * <code>map&lt;string, .Person&gt; maps = 4;</code>
       */

      public boolean containsMaps(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMaps().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, MapAndCustomNesting.Person> getMaps() {
        return getMapsMap();
      }
      /**
       * <code>map&lt;string, .Person&gt; maps = 4;</code>
       */

      public java.util.Map<java.lang.String, MapAndCustomNesting.Person> getMapsMap() {
        return internalGetMaps().getMap();
      }
      /**
       * <code>map&lt;string, .Person&gt; maps = 4;</code>
       */

      public MapAndCustomNesting.Person getMapsOrDefault(
          java.lang.String key,
          MapAndCustomNesting.Person defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, MapAndCustomNesting.Person> map =
            internalGetMaps().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .Person&gt; maps = 4;</code>
       */

      public MapAndCustomNesting.Person getMapsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, MapAndCustomNesting.Person> map =
            internalGetMaps().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMaps() {
        getMutableMaps().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .Person&gt; maps = 4;</code>
       */

      public Builder removeMaps(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableMaps().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, MapAndCustomNesting.Person>
      getMutableMaps() {
        return internalGetMutableMaps().getMutableMap();
      }
      /**
       * <code>map&lt;string, .Person&gt; maps = 4;</code>
       */
      public Builder putMaps(
          java.lang.String key,
          MapAndCustomNesting.Person value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableMaps().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .Person&gt; maps = 4;</code>
       */

      public Builder putAllMaps(
          java.util.Map<java.lang.String, MapAndCustomNesting.Person> values) {
        getMutableMaps().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Maps)
    }

    // @@protoc_insertion_point(class_scope:Maps)
    private static final MapAndCustomNesting.Maps DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MapAndCustomNesting.Maps();
    }

    public static MapAndCustomNesting.Maps getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Maps>
        PARSER = new com.google.protobuf.AbstractParser<Maps>() {
      public Maps parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Maps(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Maps> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Maps> getParserForType() {
      return PARSER;
    }

    public MapAndCustomNesting.Maps getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lists_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lists_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Maps_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Maps_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Maps_MapsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Maps_MapsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031mapAndCustomNesting.proto\"#\n\006Person\022\014\n" +
      "\004name\030\001 \002(\t\022\013\n\003age\030\002 \001(\005\"!\n\005Lists\022\030\n\007sub" +
      "ject\030\003 \003(\0132\007.Person\"[\n\004Maps\022\035\n\004maps\030\004 \003(" +
      "\0132\017.Maps.MapsEntry\0324\n\tMapsEntry\022\013\n\003key\030\001" +
      " \001(\t\022\026\n\005value\030\002 \001(\0132\007.Person:\0028\001B\025B\023MapA" +
      "ndCustomNesting"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_Lists_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Lists_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lists_descriptor,
        new java.lang.String[] { "Subject", });
    internal_static_Maps_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Maps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Maps_descriptor,
        new java.lang.String[] { "Maps", });
    internal_static_Maps_MapsEntry_descriptor =
      internal_static_Maps_descriptor.getNestedTypes().get(0);
    internal_static_Maps_MapsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Maps_MapsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
